### ISSUE TITLE
Setting the base path breaks phpcbf

### ISSUE THREAD

**Issue by villesiltala** [devgeniem/geniem-rules-codesniffer#1]
A relative base path is set in the ruleset on line 13:
https://github.com/devgeniem/geniem-rules-codesniffer/blob/d2ae48b2c65c05c340c108ad1e33b657cdc53f5d/Geniem/ruleset.xml#L13

This breaks PHP Code Beautifier execution as it tries to output the beautified code to a path relative to the currently used coding standard. Please remove this setting or find a fix for phpcbf.

**Comment by ivuorinen** [comment]
Thanks for the report!

I need to test how changing the basepath in the configuration affects our internal projects, but as a quick fix for `phpcbf` you can use this script found on the project readme:
https://github.com/devgeniem/geniem-rules-codesniffer/blob/master/README.md#usage

`vendor/bin/phpcbf --standard=phpcs.xml --basepath=. ./web/app/ ./config/`

You can override the phpcbf basepath with a runtime commandline parameter, but using `composer lint-fix` is easier to remember and you can specify what folders to check/fix automatically.

I hope this works out for you in the mean time.

**Comment by ivuorinen** [comment]
This has been resolved in the latest (1.1.0) release. I removed all `<arg>` rules from `ruleset.xml`.
The change shouldn't cause problems in ongoing projects, only have positive effects. I'm closing this as "fixed".
